name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for Sheetz? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What problem does this feature solve? What are you trying to do?
      placeholder: "I'm trying to ... but currently I have to ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work? Include example code if possible.
      placeholder: |
        ```java
        // I'd love to be able to do:
        Sheetz.read("file.xlsx", Product.class, options);
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative approaches you've considered.

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Nice to have
        - Would use immediately
        - Blocking my adoption of Sheetz
